/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as PrintRouteImport } from './routes/print'
import { Route as OcrRouteImport } from './routes/ocr'
import { Route as DataRouteImport } from './routes/data'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameRouteImport } from './routes/game.'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrRoute = OcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/ocr': typeof OcrRoute
  '/print': typeof PrintRoute
  '/templates': typeof TemplatesRoute
  '/game/': typeof GameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/ocr': typeof OcrRoute
  '/print': typeof PrintRoute
  '/templates': typeof TemplatesRoute
  '/game': typeof GameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/ocr': typeof OcrRoute
  '/print': typeof PrintRoute
  '/templates': typeof TemplatesRoute
  '/game/': typeof GameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data' | '/ocr' | '/print' | '/templates' | '/game/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data' | '/ocr' | '/print' | '/templates' | '/game'
  id: '__root__' | '/' | '/data' | '/ocr' | '/print' | '/templates' | '/game/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRoute
  OcrRoute: typeof OcrRoute
  PrintRoute: typeof PrintRoute
  TemplatesRoute: typeof TemplatesRoute
  GameRoute: typeof GameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr': {
      id: '/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game/'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRoute,
  OcrRoute: OcrRoute,
  PrintRoute: PrintRoute,
  TemplatesRoute: TemplatesRoute,
  GameRoute: GameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
